# Relaciones binarias

Una **relación binaria** $R$ sobre un conjunto $A$ es un conjunto de pares ordenados, de manera que si $x$ está relacionado con $y$, entonces $(x,y)\in R$.

In [ ]:
import numpy as np

def get_matrix(relacion, conjunto):
    """
    Completa la matriz de adyacencia.
    """
    n = len(conjunto)
    A = sorted(list(conjunto))
    #matriz adyacencia de tamaño n y llena de ceros
    M = np.zeros((n,n), dtype = "int")
    #llenar la matriz
    #La relación está conformada por un conjunto (x,y), por lo que x(0) es el
    #primero, mientras que x(1) es el segundo
    for x in relacion:
      i = A.index(x[0])
      j = A.index(x[1])
      M[i,j] = 1
    return M

def get_pairs(matriz, conjunto):
    """
    Extrae pares ordenados a partir de una matriz de adyacencia.
    """
    n = matriz.shape[0]
    A = sorted(list(conjunto))
    R =set([(A[i],A[j]) for i in range(n) for j in range(n) if matriz[i,j] == 1])
    return R

def producto_booleano(matriz1, matriz2):
    """
    Calcula el producto booleano de dos matrices cuadradas.
    """
    n = matriz1.shape[0]
    #simbolo para multiplicar matrices
    M = matriz1 @ matriz2
    for i in range (n):
      for j in range(n):
        if M [i,j] > 1:
          M[i,j] = 1
    return M
def precedence(matriz1, matriz2):
    """
    Determina si matriz1 precede a matriz2.
    """

def get_powerset(conjunto):
    """
    Calcula el conjunto potencia de un conjunto.
    """


## Ejercicio 1

Sea $A=\{1,2,\ldots,10\}$ un conjunto.

a. Se define la relación $R$ sobre $A$ de modo que $(x,y)\in R$ si $x+2=y$. Listar lo elementos de $R$.

In [ ]:
A = list(range(1,11))
R = set((x,y) for x in A for y in A if x+2 == y)
print(R)

{(2, 4), (6, 8), (4, 6), (8, 10), (5, 7), (7, 9), (1, 3), (3, 5)}


b. Completar la matriz de adyacencia de la relación $R$.

In [ ]:
matrizA = get_matrix(R, A)
print(matrizA)

[[0 0 1 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


c. Calcular la matriz $M_{R\circ R}$ y listar los pares en $R\circ R$.

In [ ]:
  M2 = producto_booleano(matrizA,matrizA)
R2 = get_pairs(M2,A)
print(M2)
print(R2)


[[0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]
{(1, 5), (3, 7), (2, 6), (6, 10), (4, 8), (5, 9)}


# Propiedades de relaciones

## Ejercicio 2.
Sea $A=\{1,2,3,4,6,8,12\}$ el conjunto de divisores propios de 24.

a. Se define la relación $R$ sobre $A$ de modo que $(x,y)\in R$ si $x$ divide a $y$. Completar la matriz de adyacencia de la relación $R$.

b. Determinar si la relación es **reflexiva**.

c. Determinar si la relación es **simétrica**.

d. Determinar si la relación es **antisimétrica**.  

e. Determinar si la relación es **transitiva**.

## Ejercicio 3.

Sea $A=\{w,x,y,z\}$ un conjunto.

a. Se define la relación $R$ sobre $\mathcal{P}(A)$ de modo que $(X,Y)\in R$ si $|X|\leq |Y|$. Completar la matriz de adyacencia de la relación $R$.

b. Determinar si la relación es **reflexiva**.

c. Determinar si la relación es **simétrica**.

d. Determinar si la relación es **antisimétrica**.  

e. Determinar si la relación es **transitiva**.